services:
  web:
    build: .
    container_name: webserver-web
    restart: unless-stopped
    ports:
      - "9100:9100"
    env_file:
      - .env
    environment:
      LOCAL_MONGO_URI: mongodb://host.docker.internal:27017/
    extra_hosts:
      - "host.docker.internal:172.18.0.1"
    volumes:
      - ./newsletters:/app/newsletters
      - ${AVD_ROOT:-/home/cpcnet/cyberclawer}:/cyberclawer
